name: utf_convert
version: 1.0.0

description: Provides common operations for manipulating Unicode sequences
author: Jack R <iambent.omnishambles@gmail.com>
homepage: https://www.github.com/jr1221/utf_convert

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.2.0